name: Sugestão de Melhoria
description: Sugerir uma nova funcionalidade ou melhoria
labels: ["enhancement"]
body:
  - type: textarea
    id: problema
    attributes:
      label: Qual problema isso resolve?
      description: Descreva a dor ou limitação atual
    validations:
      required: true
  - type: textarea
    id: solucao
    attributes:
      label: Solução proposta
      description: Como você imagina que isso funcionaria?
    validations:
      required: true
  - type: dropdown
    id: prioridade
    attributes:
      label: Prioridade sugerida
      options: [Alta, Média, Baixa]
    validations:
      required: false
